import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';

interface OptimizedImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  src: string;
  alt: string;
  blurColor?: string;
  thumbnailUrl?: string; // If known, otherwise we generate
}

// Memory cache to avoid re-blur on already loaded images across renders
const loadedImagesCache = new Set<string>();

export default function OptimizedImage({ 
  src, 
  alt, 
  className, 
  blurColor = "bg-slate-200", 
  thumbnailUrl,
  ...props 
}: OptimizedImageProps) {
  const [isLoaded, setIsLoaded] = useState(() => loadedImagesCache.has(src));
  const [hasError, setHasError] = useState(false);

  // Try to parse the Firebase Storage URL to get the thumbnail version
  // Firebase storage URL format: https://firebasestorage.googleapis.com/v0/b/bucket/o/path%2Fto%2FfileName?alt=media&token=...
  let inferredThumbUrl = thumbnailUrl;
  
  if (!inferredThumbUrl && src.includes('firebasestorage') && src.includes('chats%2F')) {
    // Basic heuristic to request the 600x600_thumb version generated by the backend
    try {
      const urlObj = new URL(src);
      const pathParts = urlObj.pathname.split('/');
      const lastPart = pathParts[pathParts.length - 1]; // "chats%2FCHAT_ID%2Fmedia%2FFILENAME"
      
      if (lastPart.includes('%2Fmedia%2F') && !lastPart.includes('_thumb_')) {
        const segments = lastPart.split('%2Fmedia%2F');
        const filename = segments[1];
        const thumbFilename = `600x600_thumb_${filename}`;
        segments[1] = thumbFilename;
        urlObj.pathname = pathParts.slice(0, -1).concat(segments.join('%2Fmedia%2F')).join('/');
        inferredThumbUrl = urlObj.toString();
      }
    } catch(e) {
      // Ignore URL parsing errors
    }
  }

  // Effect to handle URL changes
  useEffect(() => {
    if (loadedImagesCache.has(src)) {
      setIsLoaded(true);
    } else {
      setIsLoaded(false);
      setHasError(false);
    }
  }, [src]);

  return (
    <div className={`relative overflow-hidden ${className}`}>
      {/* Skeleton / Blur Background */}
      {!isLoaded && !hasError && (
        <div className={`absolute inset-0 ${blurColor} animate-pulse`} />
      )}
      
      {/* Progressive Thumbnail (if available) */}
      {!isLoaded && !hasError && inferredThumbUrl && (
        <img 
          src={inferredThumbUrl}
          alt={alt}
          className="absolute inset-0 w-full h-full object-cover blur-xl scale-110 opacity-50"
          referrerPolicy="no-referrer"
        />
      )}

      {/* Main High-Res Image */}
      <img
        src={src}
        alt={alt}
        className={`w-full h-full transition-opacity duration-500 ease-out ${isLoaded ? 'opacity-100' : 'opacity-0'} ${className}`}
        onLoad={() => {
          setIsLoaded(true);
          loadedImagesCache.add(src);
        }}
        onError={() => setHasError(true)}
        loading="lazy"
        referrerPolicy="no-referrer"
        {...props}
      />
    </div>
  );
}
